"use client";

import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import "./globals.css";
import CheckoutNav from "../components/CheckoutNav";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Le Perfume Store",
  description: "Generated by NextJs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isCheckoutPage = pathname === "/checkout";

  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        {isCheckoutPage ? <CheckoutNav /> : <Navbar />}
        {children}
        {isCheckoutPage ? '' :  <Footer />}
       
      </body>
    </html>
  );
}
